//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinia
    {
        public int id_opini { get; set; }
        public Nullable<int> ocena { get; set; }
        public string opis { get; set; }
        public Nullable<int> id_uczestnictwo { get; set; }
    
        public virtual Uczestnictwo Uczestnictwo { get; set; }
    }
}
