//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel_pracowniczy
    {
        public int id_panel { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public string stopien { get; set; }
        public string Kierownik_pesel { get; set; }
        public string Pilot_pesel { get; set; }
        public string Kierowca_pesel { get; set; }
        public string Klient_pesel { get; set; }
    
        public virtual Kierowca Kierowca { get; set; }
        public virtual Kierownik Kierownik { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Pilot Pilot { get; set; }
    }
}
