//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocja
    {
        public int id_promocji { get; set; }
        public Nullable<decimal> cena { get; set; }
        public Nullable<int> id_wycieczki { get; set; }
    
        public virtual Wycieczka Wycieczka { get; set; }
    }
}
