//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezerwacja()
        {
            this.Uczestnictwo = new HashSet<Uczestnictwo>();
        }
    
        public int numer_rezerwacji { get; set; }
        public Nullable<int> liczba_osob { get; set; }
        public Nullable<bool> stan { get; set; }
        public Nullable<decimal> zaliczka { get; set; }
        public Nullable<int> id_wycieczki { get; set; }
        public string Klient_pesel { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Wycieczka Wycieczka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uczestnictwo> Uczestnictwo { get; set; }
    }
}
