//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wycieczka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wycieczka()
        {
            this.Katalog = new HashSet<Katalog>();
            this.Rezerwacja = new HashSet<Rezerwacja>();
        }
    
        public int id_wycieczki { get; set; }
        public string nazwa { get; set; }
        public Nullable<System.DateTime> data_wyjazdu { get; set; }
        public Nullable<System.DateTime> data_powrotu { get; set; }
        public string opis { get; set; }
        public string Pilot_pesel { get; set; }
        public string Pojazd_numer_rejestracyjny { get; set; }
        public string Kierowca_pesel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Katalog> Katalog { get; set; }
        public virtual Kierowca Kierowca { get; set; }
        public virtual Pilot Pilot { get; set; }
        public virtual Pojazd Pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerwacja> Rezerwacja { get; set; }
        public virtual Promocja Promocja { get; set; }
    }
}
